theme: jekyll-theme-leap-day
title: Student High Performance Computing at SDSC
description: A program for educating and training the next generation of HPC professionals and researchers
show_downloads: false
